lib: [
  "/Users/jsullivan/reason-thrift/_esy/default/store/b/reason_thrift-7644a41c/install/default/lib/reason-thrift/META"
  "/Users/jsullivan/reason-thrift/_esy/default/store/b/reason_thrift-7644a41c/install/default/lib/reason-thrift/dune-package"
  "/Users/jsullivan/reason-thrift/_esy/default/store/b/reason_thrift-7644a41c/install/default/lib/reason-thrift/opam"
]
bin: [
  "/Users/jsullivan/reason-thrift/_esy/default/store/b/reason_thrift-7644a41c/install/default/bin/Client"
  "/Users/jsullivan/reason-thrift/_esy/default/store/b/reason_thrift-7644a41c/install/default/bin/ClientGen"
  "/Users/jsullivan/reason-thrift/_esy/default/store/b/reason_thrift-7644a41c/install/default/bin/Demo"
  "/Users/jsullivan/reason-thrift/_esy/default/store/b/reason_thrift-7644a41c/install/default/bin/ServerGen"
]
doc: [
  "/Users/jsullivan/reason-thrift/_esy/default/store/b/reason_thrift-7644a41c/install/default/doc/reason-thrift/README.md"
]
