(*
 Autogenerated by Thrift Compiler (0.13.0)

 DO NOT EDIT UNLESS YOU ARE SURE YOU KNOW WHAT YOU ARE DOING
*)

open Thrift
open Tutorial_types

class virtual iface :
object
  inherit SharedService.iface
  method virtual ping : unit
  method virtual add : Int32.t option -> Int32.t option -> Int32.t
  method virtual calculate : Int32.t option -> work option -> Int32.t
  method virtual zip : unit
end

class client : Protocol.t -> Protocol.t -> 
object
  inherit SharedService.client
  method ping : unit
  method add : Int32.t -> Int32.t -> Int32.t
  method calculate : Int32.t -> work -> Int32.t
  method zip : unit
end

class processor : iface ->
object
  inherit Processor.t

  inherit SharedService.processor
  val processMap : (string, int * Protocol.t * Protocol.t -> unit) Hashtbl.t
  method process : Protocol.t -> Protocol.t -> bool
end

