(*
 Autogenerated by Thrift Compiler (0.13.0)

 DO NOT EDIT UNLESS YOU ARE SURE YOU KNOW WHAT YOU ARE DOING
*)

open Thrift
open Shared_types

class virtual iface :
object
  method virtual getStruct : Int32.t option -> sharedStruct
end

class client : Protocol.t -> Protocol.t -> 
object
  method getStruct : Int32.t -> sharedStruct
end

class processor : iface ->
object
  inherit Processor.t

  val processMap : (string, int * Protocol.t * Protocol.t -> unit) Hashtbl.t
  method process : Protocol.t -> Protocol.t -> bool
end

