(*
 Autogenerated by Thrift Compiler (0.13.0)

 DO NOT EDIT UNLESS YOU ARE SURE YOU KNOW WHAT YOU ARE DOING
*)

open Thrift
class sharedStruct :
object ('a)
  method get_key : Int32.t option
  method grab_key : Int32.t
  method set_key : Int32.t -> unit
  method unset_key : unit
  method reset_key : unit
  method get_value : string option
  method grab_value : string
  method set_value : string -> unit
  method unset_value : unit
  method reset_value : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_sharedStruct : Protocol.t -> sharedStruct
