(*
 Autogenerated by Thrift Compiler (0.13.0)

 DO NOT EDIT UNLESS YOU ARE SURE YOU KNOW WHAT YOU ARE DOING
*)

open Thrift
open Tutorial_types
let iNT32CONSTANT = 9853l

let mAPCONSTANT = 
  (let _hm65 = Hashtbl.create 2 in
    Hashtbl.add _hm65 "goodnight" "moon";
    Hashtbl.add _hm65 "hello" "world";
    _hm65)

