(*
 Autogenerated by Thrift Compiler (0.13.0)

 DO NOT EDIT UNLESS YOU ARE SURE YOU KNOW WHAT YOU ARE DOING
*)

open Thrift
module Operation : 
sig
  type t = 
    | ADD
    | SUBTRACT
    | MULTIPLY
    | DIVIDE
  val to_i : t -> Int32.t
  val of_i : Int32.t -> t
end
class work :
object ('a)
  method get_num1 : Int32.t option
  method grab_num1 : Int32.t
  method set_num1 : Int32.t -> unit
  method reset_num1 : unit
  method get_num2 : Int32.t option
  method grab_num2 : Int32.t
  method set_num2 : Int32.t -> unit
  method unset_num2 : unit
  method reset_num2 : unit
  method get_op : Operation.t option
  method grab_op : Operation.t
  method set_op : Operation.t -> unit
  method unset_op : unit
  method reset_op : unit
  method get_comment : string option
  method grab_comment : string
  method set_comment : string -> unit
  method unset_comment : unit
  method reset_comment : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
val read_work : Protocol.t -> work
class invalidOperation :
object ('a)
  method get_whatOp : Int32.t option
  method grab_whatOp : Int32.t
  method set_whatOp : Int32.t -> unit
  method unset_whatOp : unit
  method reset_whatOp : unit
  method get_why : string option
  method grab_why : string
  method set_why : string -> unit
  method unset_why : unit
  method reset_why : unit
  method copy : 'a
  method write : Protocol.t -> unit
end
exception InvalidOperation of invalidOperation
val read_invalidOperation : Protocol.t -> invalidOperation
type myInteger = Int32.t

